// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteAPIServicesZisRegistryJobSpecsInstallSecurity struct {
	Password string `security:"scheme,type=http,subtype=basic,name=password"`
	Username string `security:"scheme,type=http,subtype=basic,name=username"`
}

func (o *DeleteAPIServicesZisRegistryJobSpecsInstallSecurity) GetPassword() string {
	if o == nil {
		return ""
	}
	return o.Password
}

func (o *DeleteAPIServicesZisRegistryJobSpecsInstallSecurity) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}

type DeleteAPIServicesZisRegistryJobSpecsInstallRequest struct {
	// (Required) The name of the job spec
	JobSpecName *string `queryParam:"style=form,explode=true,name=job_spec_name"`
}

func (o *DeleteAPIServicesZisRegistryJobSpecsInstallRequest) GetJobSpecName() *string {
	if o == nil {
		return nil
	}
	return o.JobSpecName
}

// DeleteAPIServicesZisRegistryJobSpecsInstall500ApplicationJSON - Internal Server Error
type DeleteAPIServicesZisRegistryJobSpecsInstall500ApplicationJSON struct {
}

// DeleteAPIServicesZisRegistryJobSpecsInstall404ApplicationJSON - Not Found
type DeleteAPIServicesZisRegistryJobSpecsInstall404ApplicationJSON struct {
}

// DeleteAPIServicesZisRegistryJobSpecsInstall401ApplicationJSON - Unauthorized
type DeleteAPIServicesZisRegistryJobSpecsInstall401ApplicationJSON struct {
}

// DeleteAPIServicesZisRegistryJobSpecsInstall400ApplicationJSON - Bad Request
type DeleteAPIServicesZisRegistryJobSpecsInstall400ApplicationJSON struct {
}

type DeleteAPIServicesZisRegistryJobSpecsInstallResponse struct {
	ContentType string
	Headers     map[string][]string
	StatusCode  int
	RawResponse *http.Response
	// No Content
	DeleteAPIServicesZisRegistryJobSpecsInstall204TextPlainString *string
	// Bad Request
	DeleteAPIServicesZisRegistryJobSpecsInstall400ApplicationJSONObject *DeleteAPIServicesZisRegistryJobSpecsInstall400ApplicationJSON
	// Unauthorized
	DeleteAPIServicesZisRegistryJobSpecsInstall401ApplicationJSONObject *DeleteAPIServicesZisRegistryJobSpecsInstall401ApplicationJSON
	// Not Found
	DeleteAPIServicesZisRegistryJobSpecsInstall404ApplicationJSONObject *DeleteAPIServicesZisRegistryJobSpecsInstall404ApplicationJSON
	// Internal Server Error
	DeleteAPIServicesZisRegistryJobSpecsInstall500ApplicationJSONObject *DeleteAPIServicesZisRegistryJobSpecsInstall500ApplicationJSON
}

func (o *DeleteAPIServicesZisRegistryJobSpecsInstallResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteAPIServicesZisRegistryJobSpecsInstallResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *DeleteAPIServicesZisRegistryJobSpecsInstallResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteAPIServicesZisRegistryJobSpecsInstallResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeleteAPIServicesZisRegistryJobSpecsInstallResponse) GetDeleteAPIServicesZisRegistryJobSpecsInstall204TextPlainString() *string {
	if o == nil {
		return nil
	}
	return o.DeleteAPIServicesZisRegistryJobSpecsInstall204TextPlainString
}

func (o *DeleteAPIServicesZisRegistryJobSpecsInstallResponse) GetDeleteAPIServicesZisRegistryJobSpecsInstall400ApplicationJSONObject() *DeleteAPIServicesZisRegistryJobSpecsInstall400ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.DeleteAPIServicesZisRegistryJobSpecsInstall400ApplicationJSONObject
}

func (o *DeleteAPIServicesZisRegistryJobSpecsInstallResponse) GetDeleteAPIServicesZisRegistryJobSpecsInstall401ApplicationJSONObject() *DeleteAPIServicesZisRegistryJobSpecsInstall401ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.DeleteAPIServicesZisRegistryJobSpecsInstall401ApplicationJSONObject
}

func (o *DeleteAPIServicesZisRegistryJobSpecsInstallResponse) GetDeleteAPIServicesZisRegistryJobSpecsInstall404ApplicationJSONObject() *DeleteAPIServicesZisRegistryJobSpecsInstall404ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.DeleteAPIServicesZisRegistryJobSpecsInstall404ApplicationJSONObject
}

func (o *DeleteAPIServicesZisRegistryJobSpecsInstallResponse) GetDeleteAPIServicesZisRegistryJobSpecsInstall500ApplicationJSONObject() *DeleteAPIServicesZisRegistryJobSpecsInstall500ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.DeleteAPIServicesZisRegistryJobSpecsInstall500ApplicationJSONObject
}
