// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteAPIServicesZisRegistryJobSpecsInstallRequest struct {
	// (Required) The name of the job spec
	JobSpecName *string `queryParam:"style=form,explode=true,name=job_spec_name"`
}

func (o *DeleteAPIServicesZisRegistryJobSpecsInstallRequest) GetJobSpecName() *string {
	if o == nil {
		return nil
	}
	return o.JobSpecName
}

type DeleteAPIServicesZisRegistryJobSpecsInstallResponse struct {
	// No Content
	TwoHundredAndFourTextPlainRes *string
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DeleteAPIServicesZisRegistryJobSpecsInstallResponse) GetTwoHundredAndFourTextPlainRes() *string {
	if o == nil {
		return nil
	}
	return o.TwoHundredAndFourTextPlainRes
}

func (o *DeleteAPIServicesZisRegistryJobSpecsInstallResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteAPIServicesZisRegistryJobSpecsInstallResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *DeleteAPIServicesZisRegistryJobSpecsInstallResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteAPIServicesZisRegistryJobSpecsInstallResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
