// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostAPIServicesZisRegistryJobSpecsInstallSecurity struct {
	Password string `security:"scheme,type=http,subtype=basic,name=password"`
	Username string `security:"scheme,type=http,subtype=basic,name=username"`
}

type PostAPIServicesZisRegistryJobSpecsInstallRequest struct {
	// (Required) The name of the job spec
	JobSpecName *string `queryParam:"style=form,explode=true,name=job_spec_name"`
}

// PostAPIServicesZisRegistryJobSpecsInstall500ApplicationJSON - Internal Server Error
type PostAPIServicesZisRegistryJobSpecsInstall500ApplicationJSON struct {
}

// PostAPIServicesZisRegistryJobSpecsInstall401ApplicationJSON - Unauthorized
type PostAPIServicesZisRegistryJobSpecsInstall401ApplicationJSON struct {
}

// PostAPIServicesZisRegistryJobSpecsInstall400ApplicationJSON - Bad Request
type PostAPIServicesZisRegistryJobSpecsInstall400ApplicationJSON struct {
}

type PostAPIServicesZisRegistryJobSpecsInstallResponse struct {
	ContentType string
	Headers     map[string][]string
	StatusCode  int
	RawResponse *http.Response
	// OK
	PostAPIServicesZisRegistryJobSpecsInstall200TextPlainString *string
	// Bad Request
	PostAPIServicesZisRegistryJobSpecsInstall400ApplicationJSONObject *PostAPIServicesZisRegistryJobSpecsInstall400ApplicationJSON
	// Unauthorized
	PostAPIServicesZisRegistryJobSpecsInstall401ApplicationJSONObject *PostAPIServicesZisRegistryJobSpecsInstall401ApplicationJSON
	// Internal Server Error
	PostAPIServicesZisRegistryJobSpecsInstall500ApplicationJSONObject *PostAPIServicesZisRegistryJobSpecsInstall500ApplicationJSON
}
