// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostAPIServicesZisRegistryIntegrationSecurity struct {
	Password string `security:"scheme,type=http,subtype=basic,name=password"`
	Username string `security:"scheme,type=http,subtype=basic,name=username"`
}

func (o *PostAPIServicesZisRegistryIntegrationSecurity) GetPassword() string {
	if o == nil {
		return ""
	}
	return o.Password
}

func (o *PostAPIServicesZisRegistryIntegrationSecurity) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}

type PostAPIServicesZisRegistryIntegrationRequestBody struct {
}

type PostAPIServicesZisRegistryIntegrationRequest struct {
	RequestBody *PostAPIServicesZisRegistryIntegrationRequestBody `request:"mediaType=application/json"`
	Integration string                                            `pathParam:"style=simple,explode=false,name=integration"`
}

func (o *PostAPIServicesZisRegistryIntegrationRequest) GetRequestBody() *PostAPIServicesZisRegistryIntegrationRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

func (o *PostAPIServicesZisRegistryIntegrationRequest) GetIntegration() string {
	if o == nil {
		return ""
	}
	return o.Integration
}

// PostAPIServicesZisRegistryIntegrationResponseBody - OK
type PostAPIServicesZisRegistryIntegrationResponseBody struct {
}

type PostAPIServicesZisRegistryIntegrationResponse struct {
	// OK
	TwoHundredApplicationJSONObject *PostAPIServicesZisRegistryIntegrationResponseBody
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PostAPIServicesZisRegistryIntegrationResponse) GetTwoHundredApplicationJSONObject() *PostAPIServicesZisRegistryIntegrationResponseBody {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONObject
}

func (o *PostAPIServicesZisRegistryIntegrationResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostAPIServicesZisRegistryIntegrationResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *PostAPIServicesZisRegistryIntegrationResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostAPIServicesZisRegistryIntegrationResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
