// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostAPIServicesZisRegistryIntegrationBundlesRequestBody struct {
}

type PostAPIServicesZisRegistryIntegrationBundlesRequest struct {
	RequestBody *PostAPIServicesZisRegistryIntegrationBundlesRequestBody `request:"mediaType=application/json"`
	Integration string                                                   `pathParam:"style=simple,explode=false,name=integration"`
}

func (o *PostAPIServicesZisRegistryIntegrationBundlesRequest) GetRequestBody() *PostAPIServicesZisRegistryIntegrationBundlesRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

func (o *PostAPIServicesZisRegistryIntegrationBundlesRequest) GetIntegration() string {
	if o == nil {
		return ""
	}
	return o.Integration
}

type PostAPIServicesZisRegistryIntegrationBundlesResponse struct {
	// OK
	TwoHundredTextPlainRes *string
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PostAPIServicesZisRegistryIntegrationBundlesResponse) GetTwoHundredTextPlainRes() *string {
	if o == nil {
		return nil
	}
	return o.TwoHundredTextPlainRes
}

func (o *PostAPIServicesZisRegistryIntegrationBundlesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostAPIServicesZisRegistryIntegrationBundlesResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *PostAPIServicesZisRegistryIntegrationBundlesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostAPIServicesZisRegistryIntegrationBundlesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
