// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostAPIServicesZisRegistryIntegrationBundlesSecurity struct {
	Password string `security:"scheme,type=http,subtype=basic,name=password"`
	Username string `security:"scheme,type=http,subtype=basic,name=username"`
}

type PostAPIServicesZisRegistryIntegrationBundlesRequestBody struct {
}

type PostAPIServicesZisRegistryIntegrationBundlesRequest struct {
	RequestBody *PostAPIServicesZisRegistryIntegrationBundlesRequestBody `request:"mediaType=application/json"`
	Integration string                                                   `pathParam:"style=simple,explode=false,name=integration"`
}

// PostAPIServicesZisRegistryIntegrationBundles500ApplicationJSON - Internal Server Error
type PostAPIServicesZisRegistryIntegrationBundles500ApplicationJSON struct {
}

// PostAPIServicesZisRegistryIntegrationBundles401ApplicationJSON - Unauthorized
type PostAPIServicesZisRegistryIntegrationBundles401ApplicationJSON struct {
}

// PostAPIServicesZisRegistryIntegrationBundles400ApplicationJSON - Bad Request
type PostAPIServicesZisRegistryIntegrationBundles400ApplicationJSON struct {
}

type PostAPIServicesZisRegistryIntegrationBundlesResponse struct {
	ContentType string
	Headers     map[string][]string
	StatusCode  int
	RawResponse *http.Response
	// OK
	PostAPIServicesZisRegistryIntegrationBundles200TextPlainString *string
	// Bad Request
	PostAPIServicesZisRegistryIntegrationBundles400ApplicationJSONObject *PostAPIServicesZisRegistryIntegrationBundles400ApplicationJSON
	// Unauthorized
	PostAPIServicesZisRegistryIntegrationBundles401ApplicationJSONObject *PostAPIServicesZisRegistryIntegrationBundles401ApplicationJSON
	// Internal Server Error
	PostAPIServicesZisRegistryIntegrationBundles500ApplicationJSONObject *PostAPIServicesZisRegistryIntegrationBundles500ApplicationJSON
}
