// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostAPIServicesZisRegistryJobSpecsInstallRequest struct {
	// (Required) The name of the job spec
	JobSpecName *string `queryParam:"style=form,explode=true,name=job_spec_name"`
}

func (o *PostAPIServicesZisRegistryJobSpecsInstallRequest) GetJobSpecName() *string {
	if o == nil {
		return nil
	}
	return o.JobSpecName
}

// PostAPIServicesZisRegistryJobSpecsInstall500ApplicationJSON - Internal Server Error
type PostAPIServicesZisRegistryJobSpecsInstall500ApplicationJSON struct {
}

// PostAPIServicesZisRegistryJobSpecsInstall401ApplicationJSON - Unauthorized
type PostAPIServicesZisRegistryJobSpecsInstall401ApplicationJSON struct {
}

// PostAPIServicesZisRegistryJobSpecsInstall400ApplicationJSON - Bad Request
type PostAPIServicesZisRegistryJobSpecsInstall400ApplicationJSON struct {
}

type PostAPIServicesZisRegistryJobSpecsInstallResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	PostAPIServicesZisRegistryJobSpecsInstall200TextPlainString *string
	// Bad Request
	PostAPIServicesZisRegistryJobSpecsInstall400ApplicationJSONObject *PostAPIServicesZisRegistryJobSpecsInstall400ApplicationJSON
	// Unauthorized
	PostAPIServicesZisRegistryJobSpecsInstall401ApplicationJSONObject *PostAPIServicesZisRegistryJobSpecsInstall401ApplicationJSON
	// Internal Server Error
	PostAPIServicesZisRegistryJobSpecsInstall500ApplicationJSONObject *PostAPIServicesZisRegistryJobSpecsInstall500ApplicationJSON
}

func (o *PostAPIServicesZisRegistryJobSpecsInstallResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostAPIServicesZisRegistryJobSpecsInstallResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *PostAPIServicesZisRegistryJobSpecsInstallResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostAPIServicesZisRegistryJobSpecsInstallResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PostAPIServicesZisRegistryJobSpecsInstallResponse) GetPostAPIServicesZisRegistryJobSpecsInstall200TextPlainString() *string {
	if o == nil {
		return nil
	}
	return o.PostAPIServicesZisRegistryJobSpecsInstall200TextPlainString
}

func (o *PostAPIServicesZisRegistryJobSpecsInstallResponse) GetPostAPIServicesZisRegistryJobSpecsInstall400ApplicationJSONObject() *PostAPIServicesZisRegistryJobSpecsInstall400ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.PostAPIServicesZisRegistryJobSpecsInstall400ApplicationJSONObject
}

func (o *PostAPIServicesZisRegistryJobSpecsInstallResponse) GetPostAPIServicesZisRegistryJobSpecsInstall401ApplicationJSONObject() *PostAPIServicesZisRegistryJobSpecsInstall401ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.PostAPIServicesZisRegistryJobSpecsInstall401ApplicationJSONObject
}

func (o *PostAPIServicesZisRegistryJobSpecsInstallResponse) GetPostAPIServicesZisRegistryJobSpecsInstall500ApplicationJSONObject() *PostAPIServicesZisRegistryJobSpecsInstall500ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.PostAPIServicesZisRegistryJobSpecsInstall500ApplicationJSONObject
}
