// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostAPIServicesZisRegistryIntegrationSecurity struct {
	Password string `security:"scheme,type=http,subtype=basic,name=password"`
	Username string `security:"scheme,type=http,subtype=basic,name=username"`
}

type PostAPIServicesZisRegistryIntegrationRequestBody struct {
}

type PostAPIServicesZisRegistryIntegrationRequest struct {
	RequestBody *PostAPIServicesZisRegistryIntegrationRequestBody `request:"mediaType=application/json"`
	Integration string                                            `pathParam:"style=simple,explode=false,name=integration"`
}

// PostAPIServicesZisRegistryIntegration500ApplicationJSON - Internal Server Error
type PostAPIServicesZisRegistryIntegration500ApplicationJSON struct {
}

// PostAPIServicesZisRegistryIntegration401ApplicationJSON - Unauthorized
type PostAPIServicesZisRegistryIntegration401ApplicationJSON struct {
}

// PostAPIServicesZisRegistryIntegration400ApplicationJSON - Bad Request
type PostAPIServicesZisRegistryIntegration400ApplicationJSON struct {
}

// PostAPIServicesZisRegistryIntegration200ApplicationJSON - OK
type PostAPIServicesZisRegistryIntegration200ApplicationJSON struct {
}

type PostAPIServicesZisRegistryIntegrationResponse struct {
	ContentType string
	Headers     map[string][]string
	StatusCode  int
	RawResponse *http.Response
	// OK
	PostAPIServicesZisRegistryIntegration200ApplicationJSONObject *PostAPIServicesZisRegistryIntegration200ApplicationJSON
	// Bad Request
	PostAPIServicesZisRegistryIntegration400ApplicationJSONObject *PostAPIServicesZisRegistryIntegration400ApplicationJSON
	// Unauthorized
	PostAPIServicesZisRegistryIntegration401ApplicationJSONObject *PostAPIServicesZisRegistryIntegration401ApplicationJSON
	// Internal Server Error
	PostAPIServicesZisRegistryIntegration500ApplicationJSONObject *PostAPIServicesZisRegistryIntegration500ApplicationJSON
}
