// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostAPIServicesZisRegistryJobSpecsInstallRequest struct {
	// (Required) The name of the job spec
	JobSpecName *string `queryParam:"style=form,explode=true,name=job_spec_name"`
}

func (o *PostAPIServicesZisRegistryJobSpecsInstallRequest) GetJobSpecName() *string {
	if o == nil {
		return nil
	}
	return o.JobSpecName
}

type PostAPIServicesZisRegistryJobSpecsInstallResponse struct {
	// OK
	TwoHundredTextPlainRes *string
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PostAPIServicesZisRegistryJobSpecsInstallResponse) GetTwoHundredTextPlainRes() *string {
	if o == nil {
		return nil
	}
	return o.TwoHundredTextPlainRes
}

func (o *PostAPIServicesZisRegistryJobSpecsInstallResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostAPIServicesZisRegistryJobSpecsInstallResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}

func (o *PostAPIServicesZisRegistryJobSpecsInstallResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostAPIServicesZisRegistryJobSpecsInstallResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
