// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Security struct {
	Password *string `security:"scheme,type=http,subtype=basic,name=password"`
	Username *string `security:"scheme,type=http,subtype=basic,name=username"`
}

func (o *Security) GetPassword() *string {
	if o == nil {
		return nil
	}
	return o.Password
}

func (o *Security) GetUsername() *string {
	if o == nil {
		return nil
	}
	return o.Username
}
